import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { PropsWithChildren } from "react";
import { Header } from "@/app/components/Header";
import { Providers } from "@/common/providers";
import { Toaster } from "@/common/ui/Sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body className={inter.className}>
          <Providers
          >
            <div className="relative flex min-h-screen flex-col overflow-hidden ">
              <Header />
              <main className="grow">{children}</main>
              <Toaster />
            </div>
          </Providers>
        </body>
      </html>
    </>
  );
}
